/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/impactmaker/__root";
import { Route as ProfileRouteImport } from "./routes/impactmaker/profile";
import { Route as MessagesRouteImport } from "./routes/impactmaker/messages";
import { Route as IdRouteImport } from "./routes/impactmaker/id";
import { Route as ExploreRouteImport } from "./routes/impactmaker/explore";
import { Route as IndexRouteImport } from "./routes/impactmaker/index";
import { Route as MessagesIndexRouteImport } from "./routes/impactmaker/messages/index";
import { Route as MessagesIdRouteImport } from "./routes/impactmaker/messages/$id";

const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const MessagesRoute = MessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => rootRouteImport,
} as any);
const IdRoute = IdRouteImport.update({
  id: "/id",
  path: "/id",
  getParentRoute: () => rootRouteImport,
} as any);
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MessagesRoute,
} as any);
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => MessagesRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRoute;
  "/id": typeof IdRoute;
  "/messages": typeof MessagesRouteWithChildren;
  "/profile": typeof ProfileRoute;
  "/messages/$id": typeof MessagesIdRoute;
  "/messages/": typeof MessagesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRoute;
  "/id": typeof IdRoute;
  "/profile": typeof ProfileRoute;
  "/messages/$id": typeof MessagesIdRoute;
  "/messages": typeof MessagesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRoute;
  "/id": typeof IdRoute;
  "/messages": typeof MessagesRouteWithChildren;
  "/profile": typeof ProfileRoute;
  "/messages/$id": typeof MessagesIdRoute;
  "/messages/": typeof MessagesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/explore"
    | "/id"
    | "/messages"
    | "/profile"
    | "/messages/$id"
    | "/messages/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/explore" | "/id" | "/profile" | "/messages/$id" | "/messages";
  id:
    | "__root__"
    | "/"
    | "/explore"
    | "/id"
    | "/messages"
    | "/profile"
    | "/messages/$id"
    | "/messages/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ExploreRoute: typeof ExploreRoute;
  IdRoute: typeof IdRoute;
  MessagesRoute: typeof MessagesRouteWithChildren;
  ProfileRoute: typeof ProfileRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages": {
      id: "/messages";
      path: "/messages";
      fullPath: "/messages";
      preLoaderRoute: typeof MessagesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/id": {
      id: "/id";
      path: "/id";
      fullPath: "/id";
      preLoaderRoute: typeof IdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/explore": {
      id: "/explore";
      path: "/explore";
      fullPath: "/explore";
      preLoaderRoute: typeof ExploreRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/": {
      id: "/messages/";
      path: "/";
      fullPath: "/messages/";
      preLoaderRoute: typeof MessagesIndexRouteImport;
      parentRoute: typeof MessagesRoute;
    };
    "/messages/$id": {
      id: "/messages/$id";
      path: "/$id";
      fullPath: "/messages/$id";
      preLoaderRoute: typeof MessagesIdRouteImport;
      parentRoute: typeof MessagesRoute;
    };
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute;
  MessagesIndexRoute: typeof MessagesIndexRoute;
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
};

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  IdRoute: IdRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ProfileRoute: ProfileRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
