/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/impactmaker/__root";
import { Route as ProfileRouteImport } from "./routes/impactmaker/profile";
import { Route as MessagesRouteImport } from "./routes/impactmaker/messages";
import { Route as IdRouteImport } from "./routes/impactmaker/id";
import { Route as ExploreRouteImport } from "./routes/impactmaker/explore";
import { Route as IndexRouteImport } from "./routes/impactmaker/index";

const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const MessagesRoute = MessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => rootRouteImport,
} as any);
const IdRoute = IdRouteImport.update({
  id: "/id",
  path: "/id",
  getParentRoute: () => rootRouteImport,
} as any);
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRoute;
  "/id": typeof IdRoute;
  "/messages": typeof MessagesRoute;
  "/profile": typeof ProfileRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRoute;
  "/id": typeof IdRoute;
  "/messages": typeof MessagesRoute;
  "/profile": typeof ProfileRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/explore": typeof ExploreRoute;
  "/id": typeof IdRoute;
  "/messages": typeof MessagesRoute;
  "/profile": typeof ProfileRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/explore" | "/id" | "/messages" | "/profile";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/explore" | "/id" | "/messages" | "/profile";
  id: "__root__" | "/" | "/explore" | "/id" | "/messages" | "/profile";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ExploreRoute: typeof ExploreRoute;
  IdRoute: typeof IdRoute;
  MessagesRoute: typeof MessagesRoute;
  ProfileRoute: typeof ProfileRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages": {
      id: "/messages";
      path: "/messages";
      fullPath: "/messages";
      preLoaderRoute: typeof MessagesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/id": {
      id: "/id";
      path: "/id";
      fullPath: "/id";
      preLoaderRoute: typeof IdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/explore": {
      id: "/explore";
      path: "/explore";
      fullPath: "/explore";
      preLoaderRoute: typeof ExploreRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  IdRoute: IdRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
